### ISSUE TITLE
Failed to compile example code of esp8266

### ISSUE THREAD

**Issue by 1070758302** [emqx/cloud-docs#84]
File: [/zh_CN/connect_to_deployments/esp8266.md](https://docs.emqx.cn/cloud/latest/connect_to_deployments/esp8266.html)
https://docs.emqx.cn/cloud/latest/connect_to_deployments/esp8266.html#%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81

**Comment by zibuyu1995** [comment]
@1070758302 resolve, see the https://docs.emqx.cn/cloud/latest/connect_to_deployments/esp8266.html#%E7%A4%BA%E4%BE%8B%E4%BB%A3%E7%A0%81
